### ISSUE TITLE
Pointing a gateway to a license server alias doesn't work

### ISSUE THREAD

**Issue by gadvincula** [ITRS-Group/cordial#111]
Hi,

I would like to report an issue I encountered just now. I am currently setting up a gateway and pointing it to a license server by referring to it via its alias. That alias directs you to the available licensing server. Unfortunately using the alias doesn't get the gateway licensed. I was able to determine this in Active Console as I am getting a "gateway unlicensed" message when I double click my gateway.

What i did next is to set my gateway and point it to one of the actual license servers. This solves my issue.

Does pointing to an alias a limitation of Geneos? Or is this an issue with the client's load balancer where the alias is defined?

**Comment by gvastel** [comment]
Also I noticed that the port number is not part of the command line.  This would be useful to have (as was the case with our older scripts).
In addition, it'd be good if when creating a new instance `geneos` could (a) check whether the port # is already used by another geneos component instance, and (b) whether the port # is used by any running process.

**Comment by pgalbavy-itrs** [comment]
The alias question is one for Geneos (the product) support - it is passed in on the command line and then it is down to the Gateway to do the DNS lookup. (`geneos command gateway gatewayX` to see).

The instance template is an "oops" and can be fixed in v1.5.2 later this week. I will deal with that.

**Comment by gadvincula** [comment]
I just want to share an update regarding the instance.setup.xml issue that was raised. So I tried downloading the latest Geneos utility and used it to create multiple Gateways on my test machine. The first Gateway got port 7039 which is the default. The second Gateway got port 7100 and the third Gateway got 7101.

The second and third Gateways now had the <listenPorts> <insecure> <listenPort>7xxx</listenPort> </insecure> </listenPorts> definitions in each of their instance.setup.xml. See output below:

<operatingEnvironment>
                <gatewayName>NEW_GATEWAY_2</gatewayName>
                <listenPorts>
                        <insecure>
                                <listenPort>7100</listenPort>
                        </insecure>
                </listenPorts>

        <operatingEnvironment>
                <gatewayName>NEW_GATEWAY_3</gatewayName>
                <listenPorts>
                        <insecure>
                                <listenPort>7101</listenPort>
                        </insecure>

**Comment by gadvincula** [comment]
Also, I would just like to report these warning messages whenever I am adding a Gateway using the new version of the Geneos utility.

[geneos@gcatcen003 NEW_GATEWAY_1]$ geneos add gateway NEW_GATEWAY_2
2023-06-22T15:10:58+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates foun                          d in /home/geneos/bin/geneos/gateway/templates, using internal defaults
gateway "NEW_GATEWAY_2" instance template "instance.setup.xml" rebuilt
2023-06-22T15:10:58+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates foun                          d in /home/geneos/bin/geneos/gateway/templates, using internal defaults
gateway "NEW_GATEWAY_2" added, port 7100

[geneos@gcatcen003 NEW_GATEWAY_2]$ geneos add gateway NEW_GATEWAY_3
2023-06-22T15:20:30+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates found in                      /home/geneos/bin/geneos/gateway/templates, using internal defaults
gateway "NEW_GATEWAY_3" instance template "instance.setup.xml" rebuilt
2023-06-22T15:20:30+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates found in                      /home/geneos/bin/geneos/gateway/templates, using internal defaults
gateway "NEW_GATEWAY_3" added, port 7101

I am not getting these warning messages in the previous version of the Geneos utility.

**Comment by pgalbavy-itrs** [comment]
> I just want to share an update regarding the instance.setup.xml issue that was raised. So I tried downloading the latest Geneos utility and used it to create multiple Gateways on my test machine. The first Gateway got port 7039 which is the default. The second Gateway got port 7100 and the third Gateway got 7101.
> 
> The second and third Gateways now had the 7xxx definitions in each of their instance.setup.xml.
> 
> (Please see attached)
> 
> ![Screenshot-2023-06-22](https://user-images.githubusercontent.com/114900919/247856403-ea7350c8-e52d-43b1-b6c0-7070fccd7e0e.PNG)

That's what should happen. The `instance.setup.xml` (optional) include file should always reflect the settings of the gateway. After initial creation this can be done using the `geneos rebuild` command.

Or have I misunderstood?

**Comment by pgalbavy-itrs** [comment]
> Also, I would just like to report these warning messages whenever I am adding a Gateway using the new version of the Geneos utility.
> 
> [geneos@gcatcen003 NEW_GATEWAY_1]$ geneos add gateway NEW_GATEWAY_2 2023-06-22T15:10:58+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates foun d in /home/geneos/bin/geneos/gateway/templates, using internal defaults gateway "NEW_GATEWAY_2" instance template "instance.setup.xml" rebuilt 2023-06-22T15:10:58+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates foun d in /home/geneos/bin/geneos/gateway/templates, using internal defaults gateway "NEW_GATEWAY_2" added, port 7100
> 
> [geneos@gcatcen003 NEW_GATEWAY_2]$ geneos add gateway NEW_GATEWAY_3 2023-06-22T15:20:30+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates found in /home/geneos/bin/geneos/gateway/templates, using internal defaults gateway "NEW_GATEWAY_3" instance template "instance.setup.xml" rebuilt 2023-06-22T15:20:30+08:00 WARN: tools/geneos/internal/instance/config.go:90 instance.CreateConfigFromTemplate() > No templates found in /home/geneos/bin/geneos/gateway/templates, using internal defaults gateway "NEW_GATEWAY_3" added, port 7101
> 
> I am not getting these warning messages in the previous version of the Geneos utility.

Depending on the jump you made from version 'old' to 'new' I believe the CHANGELOG mentioned that the templates directory moved and that you should use `geneos init template` to create the new templates directory or manually move any you have changed.

**Comment by gadvincula** [comment]
> > I just want to share an update regarding the instance.setup.xml issue that was raised. So I tried downloading the latest Geneos utility and used it to create multiple Gateways on my test machine. The first Gateway got port 7039 which is the default. The second Gateway got port 7100 and the third Gateway got 7101.
> > The second and third Gateways now had the 7xxx definitions in each of their instance.setup.xml.
> > (Please see attached)
> > ![Screenshot-2023-06-22](https://user-images.githubusercontent.com/114900919/247856403-ea7350c8-e52d-43b1-b6c0-7070fccd7e0e.PNG)
> 
> That's what should happen. The `instance.setup.xml` (optional) include file should always reflect the settings of the gateway. After initial creation this can be done using the `geneos rebuild` command.
> 
> Or have I misunderstood?

In the previous version of the utility, Gerard and I experienced that the instance.setup.xml had the following definition:

<listenPorts> <insecure>7xxx</insecure> </listenPorts>

instead of:

<listenPorts> <insecure> <listenPort>7xxx</listenPort> </insecure> </listenPorts>

**Comment by pgalbavy-itrs** [comment]
I cannot see what you mean, they look the same "7xxx" to me. If you mean the XML structure then the new output conforms to the schema, the old version used bare ports under `<insecure>...`

**Comment by gadvincula** [comment]
By the way I just shared that there is no more issue after using the latest Geneos utility :)

**Comment by pgalbavy-itrs** [comment]
Great, thanks for confirming. Will close.
