### ISSUE TITLE
Combine the netprobe types in the base hierarchy

### ISSUE THREAD

**Issue by cljnie** [ITRS-Group/cordial#117]
instead fo branching them out directly in the geneos hoke directory (ie. netprobe/netprobes, san/sans/floating/floatings), combine them in netprobe and, if need be, branch out there to netprobe/netprobes, netprobe/sans, netprobe/floatings

**Comment by pgalbavy-itrs** [comment]
Sounds good. Easy to do, but the challenge is the backward-compatibility code to look in the existing locations.
