### ISSUE TITLE
Concern with config file generated by `geneos add` 

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#17]
Cordial v1.3.2.

After running `geneos add host PsApac-GV-Dev-02 ssh://xxx.xxx.xxx.xxx -d -I` under user `itrs` on host `zzz.zzz.zzz.zzz` where the geneos base directory is `/opt/itrs`, it appears that:
- On host `zzz.zzz.zzz.zzz`, nothing is written to `/opt/itrs/hosts`.
  ```
  [itrs@ip-zzz-zzz-zzz-zzz ~]$ ls -ltra /opt/itrs/hosts/
  total 0
  drwxrwxr-x.  2 itrs itrs   6 Nov  9 09:39 .
  drwxr-xr-x. 11 itrs itrs 134 Nov  9 09:39 ..
  [itrs@ip-zzz-zzz-zzz-zzz ~]$
  ```
- On host `zzz.zzz.zzz.zzz`, a file `geneos-hosts.json` has been created in `/home/itrs/.config` instead of in `/home/itrs/.config/geneos` as expected.
  ```
  [itrs@ip-zzz-zzz-zzz-zzz ~]$ pwd
  /home/itrs
  [itrs@ip-zzz-zzz-zzz-zzz ~]$ ls -ltra ~/.config/
  total 8
  drwxr-xr-x.  2 itrs itrs   25 Nov  3 03:02 geneos
  drwx------. 15 itrs itrs 4096 Nov 10 06:32 ..
  -rw-r--r--.  1 itrs itrs  942 Nov 10 10:36 geneos-hosts.json
  drwxr-xr-x.  3 itrs itrs   45 Nov 10 10:36 .
  [itrs@ip-zzz-zzz-zzz-zzz ~]$ ls -ltra ~/.config/geneos
  total 4
  drwxr-xr-x. 2 itrs itrs   25 Nov  3 03:02 .
  -rw-r--r--. 1 itrs itrs 1158 Nov  9 09:39 geneos.json
  drwxr-xr-x. 3 itrs itrs   45 Nov 10 10:36 ..
  [itrs@ip-zzz-zzz-zzz-zzz ~]$
  ```

**Comment by pgalbavy-itrs** [comment]
This is a residual path left over from the before-times. The fix will require support for backward compatibility - which is not impossible but needs to be done right.

Additionally, I will see if adding YAML support as an option is feasible for not much extra work.
