### ISSUE TITLE
Unexpected connection error encountered when running `geneos ps <instance_name>` 

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#18]
Cordial v1.3.2.

After successfully adding a host named `PsApac-GV-Dev-02`, I tried running `geneos ps <instance_name>`, and got an error as
`2022-11-10T10:59:32Z ERROR: tools/geneos/internal/instance/config.go:381 instance.ReadConfig() > connection to PsApac-GV-Dev-02 failed`.

However, I can successfully passwordless ssh to the IP address as defined in `~/.config/geneos-hosts.json` for host `PsApac-GV-Dev-02`.

**Comment by pgalbavy-itrs** [comment]
The underlying issue should be fixed as per #55 - closing
