### ISSUE TITLE
Request related to remote commands

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#21]
Cordial v1.3.2.

`geneos` support for running commands on remote hosts require to have passwordless ssh.
Many ITRS customers will not allow passwordless ssh in their network.  To get around this while maintaining support for remote commands, could `geneos` be enhanced to support host passwords in config files (preferably stored as aes encoded) or passwords to be entered manually by the user at runtime.

**Comment by pgalbavy-itrs** [comment]
I like this. Now we can store encoded passwords in configs this may be an acceptable compromise for some users.

Will check code to see how much work this is.

**Comment by pgalbavy-itrs** [comment]
For reference, these are the authentication methods available in the SSH package used:

https://pkg.go.dev/golang.org/x/crypto/ssh#AuthMethod

The two we are interested in here are the Password/PasswordCallback and the KeyboardInteractive - we could, for those who want the feature set but do not want to store passwords in anyway, offer to prompt once per run. This would be annoying for the average user but for a single `geneos start` call may be acceptable. Additionally, if we implement a long-running web interface, for example, then loading the credentials this way may also be acceptable.

**Comment by pgalbavy-itrs** [comment]
Passwords are now implemented, via the `geneos set host` command, but this needs documenting and further features added.

Additionally, we need to make use of something like the `memguard` package or similar to protect in-memory credentials in the future.

**Comment by pgalbavy-itrs** [comment]
This is done, going to close while leaving memguard questions for a future release.
