### ISSUE TITLE
Enhancement request related to `geneos ls` & `geneos ps`

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#35]
Currently, there is a command to list all instances (`geneos ls`) and a command to list all running instances (`geneos ps`).
It'd be nice to have a command showing the status of instances (enabled / disabled, not-running / running details if running, ...).  In short something like a combination of `ls` & `ps`, with the disabled status in addition.

**Comment by pgalbavy-itrs** [comment]
`geneos ls` will decorate the name with `*` for disabled and `+` for protected. We could have more explicit flags, which is already the case for CSVB and JSON output option I believe.

`geneos ps` should show something for protected instances, but disabled would not be running, right?

**Comment by gvastel** [comment]
What is a "protected instance"?

**Comment by gvastel** [comment]
Sorry for the hasty question.  Found the answer in the README.md file.
