### ISSUE TITLE
Issue with `geneos set global`

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#36]
When trying to use `geneos set global`, it looks like the value specified is not set anywhere.
Looked for it in `~/.config/geneos/geneos.json` and `/opt/itrs/*/*s/*/*` (also `/etc/geneos/geneos.json`), but could not find any trace of the values set.  Same behaviour applies to supported parameters & non-supported parameters.

On the other hand changes made with `geneos set user` get reflected in `~/.config/geneos/geneos.json`.

Am I missing something?

**Comment by gvastel** [comment]
Works if the command is run as `sudo geneos set global`.  In that case the updated parameter can be found in file `/etc/geneos/geneos.json`.

**Comment by pgalbavy-itrs** [comment]
There's more going on here, need to untangle. `geneos set global` should update the `/etc/geneos/geneos.json` file but leave ownership and permissions alone. From reviewing the code it actually rewrites the file (semi-atomically) and then if running under `sudo` will set the ownership to the non-root user calling it. This isn't right.

**Comment by pgalbavy-itrs** [comment]
I think I know how to do this, but not going to make changes now.

There needs to be common handling of file ownership when running as root and also, potentially differently, when using `sudo` as environment variables indicate the user of the original caller.

**Comment by pgalbavy-itrs** [comment]
`set global` and friends have now been removed - `set user` etc. are now `geneos config set` etc.

This removes the ambiguities. A global file is still supported - `/etc/geneos/geneos.json` etc. - but has to be edited by hand.
