### ISSUE TITLE
Issue with `geneos update`

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#38]
According to the documentation, the `geneos update` command should stop matching instances before updating the symlink, and restart them after the update is done.
Based on a test today, this is apparently not the case.  
Test was done with netprobe and it was observed that the pid of netrobe processes was the same before & after the `geneos update` command was run.  At the same time, the symlink (active_prod) had been changed.

**Comment by pgalbavy-itrs** [comment]
Only with the `-R` flag applied. This may be the wrong way around, as the install directory should probably not be allowed to change under the running process.

**Comment by pgalbavy-itrs** [comment]
Need to think about this. Perhaps without the `-R` or `--force` flag (either) updates are rejected for links that are in use by running processes?
