### ISSUE TITLE
`geneos aes decode` vs `geneos aes decode`

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#54]
When using `geneos aes encode` withough defining TYPE & NAME, I get 1 encoded output for each keyfile configured in the instance json config file of gateways, netprobes & sans (parameter `keyfile`).
However when I use `geneos aes decode` without defining TYPE & NAME, decoding id done only with the keyfiles condifured for gateway instances. I get the exact same behavior if I use `geneos aes decode gateway`.
Also if I use `geneos aes decode netprobe`, I get no respose eventhough there are keyfiles defined in the netprobe instance json config files.

Is this an expected behaviour?

**Comment by gvastel** [comment]
Now looks ok.
```
$ geneos aes decode -p +encs+D0C22839F72FFDC1CB0C00220D0057FB
gateway "gw_test1": "qwerty"
gateway "ip-172-31-0-160.ap-southeast-1.compute.internal": open /opt/itrs/gateway/gateway_shared/keyfiles/AA173C7F.aes: no such file or directory
netprobe "np_testX": "qwerty"
```

Note that for components which "fail to decode with keyfile", no output in printed while if the component's keyfile was passed with option `-k`, an error message would be printed.
```
$ geneos aes decode -p +encs+D0C22839F72FFDC1CB0C00220D0057FB netprobe
netprobe "np_testX": "qwerty"
$ grep keyfile /opt/itrs/netprobe/netprobes/*/*.json
/opt/itrs/netprobe/netprobes/np_test4/netprobe.json:  "keyfile": "/opt/itrs/netprobe/netprobe_shared/keyfiles/130FE478.aes",
/opt/itrs/netprobe/netprobes/np_testA/netprobe.json:  "keyfile": "/tmp/qwerty.aes",
/opt/itrs/netprobe/netprobes/np_testX/netprobe.json:  "keyfile": "/tmp/xyz.aes",
]$ geneos aes decode -p +encs+D0C22839F72FFDC1CB0C00220D0057FB -k /opt/itrs/netprobe/netprobe_shared/keyfiles/130FE478.aes
Error: decode failed with key file(s) provided
$ geneos aes decode -p +encs+D0C22839F72FFDC1CB0C00220D0057FB -k /tmp/qwerty.aes
Error: decode failed with key file(s) provided
$ geneos aes decode -p +encs+D0C22839F72FFDC1CB0C00220D0057FB -k /tmp/xyz.aes
decoded: qwerty
$ geneos aes decode -p +encs+D0C22839F72FFDC1CB0C00220D0057FB netprobe np_testX
netprobe "np_testX": "qwerty"
```
At the same time. for components where keyfile cannot be found, an error message is printed.

Might be good to show all output with the corresponding error message.

**Comment by pgalbavy-itrs** [comment]
This is intentional (and I believe documented). The "decode for instances" only returns values that appear to be valid UTF-8 strings as decoding with the wrong keyfile results in gibberish and only outputs valid efforts, while trying with a specific file either works or does not.

This may be confusing, but not sure printing errors would help the user.
