### ISSUE TITLE
Question about `geneos restart`

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#58]
In the legacy control scripts, there was a waiting time between the instance stop and the instance start.
- Is there any such wait / delay in `geneos restart`?
  Looks like this is not the case, but lets make sure. :grin:
- If there is a wait/delay, can it be controlled by the user?

**Comment by pgalbavy-itrs** [comment]
No, this is intentional. The program waits for the process to exit before returning, ultimately issuing a SIGKILL if it does not. Artificial delays were just because of the way the old bash scripts (did not) function.
