### ISSUE TITLE
About `host` parameters 

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#59]
`geneos` has a `geneos set host` command to set host parameters, but has no `geneos show host` command to view the host parameters.
Host parameters can be viewed by reading file `~/.config/geneos/hosts.json`, but ...

Having a `geneos show host` command would be good to have.

**Comment by pgalbavy-itrs** [comment]
Please give the new `show hosts` command a try. If good, we can close this.

Help docs yet being written.

**Comment by gvastel** [comment]
Looks ok.
Closing this issue.
